In [1]:
# Task 1 Convert List to 1D Array

import numpy as np

# Original list of numeric values
Original_List=[12.23, 13.32, 100, 36.32]

# Convert to one-dimensional NumPy array
array=np.array(Original_List)

# Display the results
print("Original List:", Original_List)
print("One-dimensional NumPy array:", array)

Original List: [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


In [3]:
# Task 2

import numpy as np

# Create a 3x3 matrix with values from 2 to 10
matrix=np.arange(2,11).reshape(3,3)

print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [4]:
# Task 3

import numpy as np

vector=np.zeros(10)

print("Orginal vector:", vector)

vector[6]=11

print("Updated vector", vector)


Orginal vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated vector [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [5]:
# Task 4

import numpy as np

array1=np.arange(12,38)

print(array1)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [6]:
# Task 5

import numpy as np

Original_array=np.array([1, 2, 3, 4])

print("Orginal Array:", Original_array)

float_array=Original_array.astype(np.float16)

print("Float Array:", float_array)

Orginal Array: [1 2 3 4]
Float Array: [1. 2. 3. 4.]


In [14]:
# Task 6

import numpy as np

# Fahrenheit values
fahrenheit = np.array([0, 12, 45.21, 34, 99.91, 32])
print("Values in Fahrenheit degrees:", fahrenheit)

# Convert to Centigrade
centigrade = (fahrenheit - 32) * 5 / 9
print("Values in Centigrade degrees:", np.round(centigrade,2))

# Centigrade values in a NumPy array
centigrade = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0.0])
print("Values in Centigrade degrees:", centigrade)

# Convert to Fahrenheit
fahrenheit=centigrade*9/5+32
print("Values in Fahrenheit degrees:", np.round(fahrenheit,2))




Values in Fahrenheit degrees: [ 0.   12.   45.21 34.   99.91 32.  ]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Centigrade degrees: [-17.78 -11.11   7.34   1.11  37.73   0.  ]
Values in Fahrenheit degrees: [-0.   12.   45.21 34.   99.91 32.  ]


In [18]:
# Task 7

import numpy as np

# Orginal array
Original_array=np.array([10, 20, 30])
print("Orginal array:", Original_array)

# Append values
new_array=np.append(Original_array, [40,50,60,70,80,90])
print("Array after appending:", new_array)



Orginal array: [10 20 30]
Array after appending: [10 20 30 40 50 60 70 80 90]


In [22]:
# Task 8

import numpy as np

# Create a random array of 10 elements (values between 0 and 1)
arr = np.random.rand(10)
print("Random Array:", arr)

# Calculate mean
mean_val=np.mean(arr)
print("Mean:", mean_val)

# Calculate median
median_val = np.median(arr)
print("Median:", median_val)

# Calculate standard deviation
std_val = np.std(arr)
print("Standard Deviation:", std_val)

Random Array: [0.73363902 0.29177443 0.07314535 0.5689857  0.55003087 0.59363892
 0.00703356 0.61805367 0.11051215 0.45059059]
Mean: 0.399740426654505
Median: 0.5003107296275786
Standard Deviation: 0.2463240074800294


In [21]:
# Task 9

import numpy as np

data=np.random.randn(10,10)
print(data)

min=np.min(data)
print("Min value:", min)

max=np.max(data)
print("Max value:", max)



[[ 2.56737831 -1.18104715  1.30249198 -1.09523623  1.1981411   0.20586661
  -1.9139065  -1.2266885  -0.00903477  0.51801697]
 [ 0.04941222  0.49509247  1.01068329  0.46235277  0.45512862  0.12104691
  -0.78775401 -0.91250396  1.6790216  -0.75526483]
 [ 1.04393447 -1.23236815 -0.22236649 -0.25988253  0.24091483 -1.59629328
   0.23352841  0.29773408  0.67053504 -0.88563795]
 [-1.21888008 -0.17707115  0.62375174  0.52431188 -0.66874206  0.01251124
  -1.82059053  0.59012493  0.23993607  0.13242279]
 [-1.57433417 -1.92140152  0.43472107 -1.4036962  -0.09366354  0.31361674
  -0.87265208  0.04741759 -0.67853506  0.90359391]
 [-0.256448   -1.23310188 -0.02337983  0.96119069 -1.88263902  1.66181373
  -0.14731952  0.60347078 -2.59169235 -0.14087939]
 [-0.55459462 -0.00749572  1.18781829  0.94127412  0.00721331  0.78969083
  -0.01255513  0.63090987  0.29473599 -0.13741274]
 [ 0.51644801 -0.0642529   1.02305587 -0.23234037  1.47459575  0.70267254
  -1.01915626  0.02728454 -1.06355139  0.2748004 ]


In [20]:
# Task 10 

import numpy as np

Array=np.random.randn(3,3,3)

print(Array)

[[[-0.450081    1.17448799 -0.85765542]
  [ 0.38203746  0.53496813 -0.46026147]
  [ 0.62350913  0.67804426 -3.06313153]]

 [[-0.53649465  0.26763591 -0.14791622]
  [ 1.34303985 -0.0410331  -0.05286648]
  [-1.09992388 -0.97513557 -0.92466737]]

 [[-0.6326496  -1.65239877 -0.29983794]
  [ 0.37697096  1.11662069 -0.94475581]
  [-0.46925119 -1.00135303  0.42115725]]]
